/* notebook.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from notebook.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define SMART_TYPE_NOTEBOOK (smart_notebook_get_type ())
#define SMART_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SMART_TYPE_NOTEBOOK, SmartNotebook))
#define SMART_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SMART_TYPE_NOTEBOOK, SmartNotebookClass))
#define SMART_IS_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SMART_TYPE_NOTEBOOK))
#define SMART_IS_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SMART_TYPE_NOTEBOOK))
#define SMART_NOTEBOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SMART_TYPE_NOTEBOOK, SmartNotebookClass))

typedef struct _SmartNotebook SmartNotebook;
typedef struct _SmartNotebookClass SmartNotebookClass;
typedef struct _SmartNotebookPrivate SmartNotebookPrivate;

#define SMART_TYPE_NOTEBOOK_TAB (smart_notebook_tab_get_type ())
#define SMART_NOTEBOOK_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTab))
#define SMART_NOTEBOOK_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTabClass))
#define SMART_IS_NOTEBOOK_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SMART_TYPE_NOTEBOOK_TAB))
#define SMART_IS_NOTEBOOK_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SMART_TYPE_NOTEBOOK_TAB))
#define SMART_NOTEBOOK_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTabClass))

typedef struct _SmartNotebookTab SmartNotebookTab;
typedef struct _SmartNotebookTabClass SmartNotebookTabClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))

struct _SmartNotebook {
	GtkNotebook parent_instance;
	SmartNotebookPrivate * priv;
};

struct _SmartNotebookClass {
	GtkNotebookClass parent_class;
};

struct _SmartNotebookPrivate {
	GtkHBox* action_hbox;
	GtkButton* _new_tab_button;
	GtkButton* _tab_selector_button;
	GtkMenu* _tab_selector_menu;
	GPtrArray* _tabs;
	gboolean _has_new_tab_button;
	gboolean _has_tab_selector_button;
};


static gpointer smart_notebook_parent_class = NULL;

GType smart_notebook_get_type (void) G_GNUC_CONST;
GType smart_notebook_tab_get_type (void) G_GNUC_CONST;
#define SMART_NOTEBOOK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SMART_TYPE_NOTEBOOK, SmartNotebookPrivate))
enum  {
	SMART_NOTEBOOK_DUMMY_PROPERTY,
	SMART_NOTEBOOK_NEW_TAB_BUTTON,
	SMART_NOTEBOOK_TAB_SELECTOR_BUTTON,
	SMART_NOTEBOOK_TAB_SELECTOR_MENU,
	SMART_NOTEBOOK_TABS,
	SMART_NOTEBOOK_HAS_NEW_TAB_BUTTON,
	SMART_NOTEBOOK_HAS_TAB_SELECTOR_BUTTON
};
gint smart_notebook_append_tab (SmartNotebook* self, SmartNotebookTab* tab);
GtkWidget* smart_notebook_tab_get_child (SmartNotebookTab* self);
GtkHBox* smart_notebook_tab_get_tab_hbox (SmartNotebookTab* self);
gint smart_notebook_insert_tab (SmartNotebook* self, SmartNotebookTab* tab, gint position);
void smart_notebook_remove_tab (SmartNotebook* self, SmartNotebookTab* tab);
void smart_notebook_load_positions (SmartNotebook* self, const gchar* positions_file);
void smart_notebook_store_positions (SmartNotebook* self, const gchar* positions_file);
SmartNotebook* smart_notebook_new (const gchar* name);
SmartNotebook* smart_notebook_construct (GType object_type, const gchar* name);
static void _g_object_unref0_ (gpointer var);
void smart_notebook_set_has_new_tab_button (SmartNotebook* self, gboolean value);
GtkButton* smart_notebook_get_new_tab_button (SmartNotebook* self);
gboolean smart_notebook_get_has_new_tab_button (SmartNotebook* self);
GtkButton* smart_notebook_get_tab_selector_button (SmartNotebook* self);
gboolean smart_notebook_get_has_tab_selector_button (SmartNotebook* self);
GtkMenu* smart_notebook_get_tab_selector_menu (SmartNotebook* self);
GPtrArray* smart_notebook_get_tabs (SmartNotebook* self);
void smart_notebook_set_has_tab_selector_button (SmartNotebook* self, gboolean value);
static void g_cclosure_user_marshal_VOID__OBJECT_UINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void smart_notebook_finalize (GObject* obj);
static void _vala_smart_notebook_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_smart_notebook_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


gint smart_notebook_append_tab (SmartNotebook* self, SmartNotebookTab* tab) {
	gint result = 0;
	GtkWidget* _tmp0_ = NULL;
	GtkHBox* _tmp1_ = NULL;
	gint _tmp2_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (tab != NULL, 0);
	_tmp0_ = smart_notebook_tab_get_child (tab);
	_tmp1_ = smart_notebook_tab_get_tab_hbox (tab);
	_tmp2_ = gtk_notebook_append_page ((GtkNotebook*) self, _tmp0_, (GtkWidget*) _tmp1_);
	result = _tmp2_;
	return result;
}


gint smart_notebook_insert_tab (SmartNotebook* self, SmartNotebookTab* tab, gint position) {
	gint result = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (tab != NULL, 0);
	result = -1;
	return result;
}


void smart_notebook_remove_tab (SmartNotebook* self, SmartNotebookTab* tab) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (tab != NULL);
}


void smart_notebook_load_positions (SmartNotebook* self, const gchar* positions_file) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (positions_file != NULL);
}


void smart_notebook_store_positions (SmartNotebook* self, const gchar* positions_file) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (positions_file != NULL);
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


SmartNotebook* smart_notebook_construct (GType object_type, const gchar* name) {
	SmartNotebook * self = NULL;
	GPtrArray* _tmp0_ = NULL;
	GtkHBox* _tmp1_ = NULL;
	GtkImage* add_img = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkImage* _tmp3_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (SmartNotebook*) g_object_new (object_type, NULL);
	gtk_widget_set_name ((GtkWidget*) self, name);
	_tmp0_ = g_ptr_array_new_with_free_func (_g_object_unref0_);
	_g_ptr_array_unref0 (self->priv->_tabs);
	self->priv->_tabs = _tmp0_;
	_tmp1_ = (GtkHBox*) gtk_hbox_new (FALSE, 6);
	_g_object_unref0 (self->priv->action_hbox);
	self->priv->action_hbox = g_object_ref_sink (_tmp1_);
	gtk_notebook_set_action_widget ((GtkNotebook*) self, (GtkWidget*) self->priv->action_hbox, GTK_PACK_END);
	_tmp2_ = (GtkButton*) gtk_button_new ();
	_g_object_unref0 (self->priv->_new_tab_button);
	self->priv->_new_tab_button = g_object_ref_sink (_tmp2_);
	gtk_button_set_relief (self->priv->_new_tab_button, GTK_RELIEF_NONE);
	gtk_button_set_focus_on_click (self->priv->_new_tab_button, FALSE);
	_tmp3_ = (GtkImage*) gtk_image_new_from_stock (GTK_STOCK_ADD, GTK_ICON_SIZE_MENU);
	_g_object_unref0 (add_img);
	add_img = g_object_ref_sink (_tmp3_);
	gtk_container_add ((GtkContainer*) self->priv->_new_tab_button, (GtkWidget*) add_img);
	gtk_box_pack_start ((GtkBox*) self->priv->action_hbox, (GtkWidget*) self->priv->_new_tab_button, FALSE, TRUE, (guint) 0);
	gtk_widget_show_all ((GtkWidget*) self->priv->_new_tab_button);
	gtk_widget_show_all ((GtkWidget*) self->priv->action_hbox);
	smart_notebook_set_has_new_tab_button (self, TRUE);
	self->priv->_has_tab_selector_button = TRUE;
	_g_object_unref0 (add_img);
	return self;
}


SmartNotebook* smart_notebook_new (const gchar* name) {
	return smart_notebook_construct (SMART_TYPE_NOTEBOOK, name);
}


GtkButton* smart_notebook_get_new_tab_button (SmartNotebook* self) {
	GtkButton* result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = smart_notebook_get_has_new_tab_button (self);
	if (!_tmp0_) {
		result = NULL;
		return result;
	}
	result = self->priv->_new_tab_button;
	return result;
}


GtkButton* smart_notebook_get_tab_selector_button (SmartNotebook* self) {
	GtkButton* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (!self->priv->_has_tab_selector_button) {
		result = NULL;
		return result;
	}
	result = self->priv->_tab_selector_button;
	return result;
}


GtkMenu* smart_notebook_get_tab_selector_menu (SmartNotebook* self) {
	GtkMenu* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (!self->priv->_has_tab_selector_button) {
		result = NULL;
		return result;
	}
	result = self->priv->_tab_selector_menu;
	return result;
}


GPtrArray* smart_notebook_get_tabs (SmartNotebook* self) {
	GPtrArray* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_tabs;
	return result;
}


gboolean smart_notebook_get_has_new_tab_button (SmartNotebook* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_has_new_tab_button;
	return result;
}


void smart_notebook_set_has_new_tab_button (SmartNotebook* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_has_new_tab_button = value;
	if (self->priv->_has_new_tab_button) {
		gtk_widget_show_all ((GtkWidget*) self->priv->_new_tab_button);
	} else {
		gtk_widget_hide_all ((GtkWidget*) self->priv->_new_tab_button);
	}
	g_object_notify ((GObject *) self, "has-new-tab-button");
}


gboolean smart_notebook_get_has_tab_selector_button (SmartNotebook* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_has_tab_selector_button;
	return result;
}


void smart_notebook_set_has_tab_selector_button (SmartNotebook* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_has_tab_selector_button = value;
	g_object_notify ((GObject *) self, "has-tab-selector-button");
}


static void g_cclosure_user_marshal_VOID__OBJECT_UINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__OBJECT_UINT) (gpointer data1, gpointer arg_1, guint arg_2, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_UINT callback;
	register GCClosure * cc;
	register gpointer data1, data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__OBJECT_UINT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_object (param_values + 1), g_value_get_uint (param_values + 2), data2);
}


static void smart_notebook_class_init (SmartNotebookClass * klass) {
	smart_notebook_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SmartNotebookPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_smart_notebook_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_smart_notebook_set_property;
	G_OBJECT_CLASS (klass)->finalize = smart_notebook_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_NEW_TAB_BUTTON, g_param_spec_object ("new-tab-button", "new-tab-button", "new-tab-button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_TAB_SELECTOR_BUTTON, g_param_spec_object ("tab-selector-button", "tab-selector-button", "tab-selector-button", GTK_TYPE_BUTTON, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_TAB_SELECTOR_MENU, g_param_spec_object ("tab-selector-menu", "tab-selector-menu", "tab-selector-menu", GTK_TYPE_MENU, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_TABS, g_param_spec_boxed ("tabs", "tabs", "tabs", G_TYPE_PTR_ARRAY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_HAS_NEW_TAB_BUTTON, g_param_spec_boolean ("has-new-tab-button", "has-new-tab-button", "has-new-tab-button", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SMART_NOTEBOOK_HAS_TAB_SELECTOR_BUTTON, g_param_spec_boolean ("has-tab-selector-button", "has-tab-selector-button", "has-tab-selector-button", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("tab_attached", SMART_TYPE_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, SMART_TYPE_NOTEBOOK_TAB);
	g_signal_new ("tab_detached", SMART_TYPE_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, SMART_TYPE_NOTEBOOK_TAB);
	g_signal_new ("tab_reordered", SMART_TYPE_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_UINT, G_TYPE_NONE, 2, SMART_TYPE_NOTEBOOK_TAB, G_TYPE_UINT);
	g_signal_new ("tabs_stored", SMART_TYPE_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("tabs_loaded", SMART_TYPE_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void smart_notebook_instance_init (SmartNotebook * self) {
	self->priv = SMART_NOTEBOOK_GET_PRIVATE (self);
}


static void smart_notebook_finalize (GObject* obj) {
	SmartNotebook * self;
	self = SMART_NOTEBOOK (obj);
	_g_object_unref0 (self->priv->action_hbox);
	_g_object_unref0 (self->priv->_new_tab_button);
	_g_object_unref0 (self->priv->_tab_selector_button);
	_g_object_unref0 (self->priv->_tab_selector_menu);
	_g_ptr_array_unref0 (self->priv->_tabs);
	G_OBJECT_CLASS (smart_notebook_parent_class)->finalize (obj);
}


GType smart_notebook_get_type (void) {
	static volatile gsize smart_notebook_type_id__volatile = 0;
	if (g_once_init_enter (&smart_notebook_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SmartNotebookClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) smart_notebook_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SmartNotebook), 0, (GInstanceInitFunc) smart_notebook_instance_init, NULL };
		GType smart_notebook_type_id;
		smart_notebook_type_id = g_type_register_static (GTK_TYPE_NOTEBOOK, "SmartNotebook", &g_define_type_info, 0);
		g_once_init_leave (&smart_notebook_type_id__volatile, smart_notebook_type_id);
	}
	return smart_notebook_type_id__volatile;
}


static void _vala_smart_notebook_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SmartNotebook * self;
	self = SMART_NOTEBOOK (object);
	switch (property_id) {
		case SMART_NOTEBOOK_NEW_TAB_BUTTON:
		g_value_set_object (value, smart_notebook_get_new_tab_button (self));
		break;
		case SMART_NOTEBOOK_TAB_SELECTOR_BUTTON:
		g_value_set_object (value, smart_notebook_get_tab_selector_button (self));
		break;
		case SMART_NOTEBOOK_TAB_SELECTOR_MENU:
		g_value_set_object (value, smart_notebook_get_tab_selector_menu (self));
		break;
		case SMART_NOTEBOOK_TABS:
		g_value_set_boxed (value, smart_notebook_get_tabs (self));
		break;
		case SMART_NOTEBOOK_HAS_NEW_TAB_BUTTON:
		g_value_set_boolean (value, smart_notebook_get_has_new_tab_button (self));
		break;
		case SMART_NOTEBOOK_HAS_TAB_SELECTOR_BUTTON:
		g_value_set_boolean (value, smart_notebook_get_has_tab_selector_button (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_smart_notebook_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SmartNotebook * self;
	self = SMART_NOTEBOOK (object);
	switch (property_id) {
		case SMART_NOTEBOOK_HAS_NEW_TAB_BUTTON:
		smart_notebook_set_has_new_tab_button (self, g_value_get_boolean (value));
		break;
		case SMART_NOTEBOOK_HAS_TAB_SELECTOR_BUTTON:
		smart_notebook_set_has_tab_selector_button (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



