/* test.c generated by valac 0.11.6.38-0ec3, the Vala compiler
 * generated from test.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define SMART_TYPE_NOTEBOOK_MANAGER (smart_notebook_manager_get_type ())
#define SMART_NOTEBOOK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SMART_TYPE_NOTEBOOK_MANAGER, SmartNotebookManager))
#define SMART_NOTEBOOK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SMART_TYPE_NOTEBOOK_MANAGER, SmartNotebookManagerClass))
#define SMART_IS_NOTEBOOK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SMART_TYPE_NOTEBOOK_MANAGER))
#define SMART_IS_NOTEBOOK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SMART_TYPE_NOTEBOOK_MANAGER))
#define SMART_NOTEBOOK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SMART_TYPE_NOTEBOOK_MANAGER, SmartNotebookManagerClass))

typedef struct _SmartNotebookManager SmartNotebookManager;
typedef struct _SmartNotebookManagerClass SmartNotebookManagerClass;

#define SMART_TYPE_NOTEBOOK (smart_notebook_get_type ())
#define SMART_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SMART_TYPE_NOTEBOOK, SmartNotebook))
#define SMART_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SMART_TYPE_NOTEBOOK, SmartNotebookClass))
#define SMART_IS_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SMART_TYPE_NOTEBOOK))
#define SMART_IS_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SMART_TYPE_NOTEBOOK))
#define SMART_NOTEBOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SMART_TYPE_NOTEBOOK, SmartNotebookClass))

typedef struct _SmartNotebook SmartNotebook;
typedef struct _SmartNotebookClass SmartNotebookClass;

#define SMART_TYPE_NOTEBOOK_TAB (smart_notebook_tab_get_type ())
#define SMART_NOTEBOOK_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTab))
#define SMART_NOTEBOOK_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTabClass))
#define SMART_IS_NOTEBOOK_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SMART_TYPE_NOTEBOOK_TAB))
#define SMART_IS_NOTEBOOK_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SMART_TYPE_NOTEBOOK_TAB))
#define SMART_NOTEBOOK_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SMART_TYPE_NOTEBOOK_TAB, SmartNotebookTabClass))

typedef struct _SmartNotebookTab SmartNotebookTab;
typedef struct _SmartNotebookTabClass SmartNotebookTabClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



gint smart_main (gchar** args, int args_length1);
SmartNotebookManager* smart_notebook_manager_new (const gchar* name);
SmartNotebookManager* smart_notebook_manager_construct (GType object_type, const gchar* name);
GType smart_notebook_manager_get_type (void) G_GNUC_CONST;
SmartNotebook* smart_notebook_new (const gchar* name);
SmartNotebook* smart_notebook_construct (GType object_type, const gchar* name);
GType smart_notebook_get_type (void) G_GNUC_CONST;
GType smart_notebook_tab_get_type (void) G_GNUC_CONST;
SmartNotebookTab* smart_notebook_tab_new_full (GtkWidget* child, GtkWidget* label, GtkImage* icon, gboolean can_close, GtkWidget* menu_label);
SmartNotebookTab* smart_notebook_tab_construct_full (GType object_type, GtkWidget* child, GtkWidget* label, GtkImage* icon, gboolean can_close, GtkWidget* menu_label);
SmartNotebookTab* smart_notebook_tab_new (GtkWidget* child, GtkWidget* label);
SmartNotebookTab* smart_notebook_tab_construct (GType object_type, GtkWidget* child, GtkWidget* label);
void smart_notebook_manager_register_notebook (SmartNotebookManager* self, SmartNotebook* smart_notebook);
void smart_notebook_manager_store_notebook_tab_positions (SmartNotebookManager* self, const gchar* positions_file);
gint smart_notebook_append_tab (SmartNotebook* self, SmartNotebookTab* tab);
void smart_notebook_tab_set_reorderable (SmartNotebookTab* self, gboolean value);
void smart_notebook_tab_set_detachable (SmartNotebookTab* self, gboolean value);
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self);


static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self) {
	gtk_main_quit ();
}


gint smart_main (gchar** args, int args_length1) {
	gint result = 0;
	GtkWindow* _tmp0_ = NULL;
	GtkWindow* win;
	SmartNotebookManager* _tmp1_ = NULL;
	SmartNotebookManager* mgr;
	SmartNotebook* _tmp2_ = NULL;
	SmartNotebook* nb;
	SmartNotebookTab* tab1 = NULL;
	SmartNotebookTab* tab2 = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_;
	GtkLabel* _tmp7_ = NULL;
	GtkLabel* _tmp8_;
	SmartNotebookTab* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	GtkLabel* _tmp11_;
	GtkLabel* _tmp12_ = NULL;
	GtkLabel* _tmp13_;
	SmartNotebookTab* _tmp14_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	win = g_object_ref_sink (_tmp0_);
	_tmp1_ = smart_notebook_manager_new ("nbmgr");
	mgr = _tmp1_;
	_tmp2_ = smart_notebook_new ("nb1");
	nb = g_object_ref_sink (_tmp2_);
	_tmp3_ = (GtkLabel*) gtk_label_new ("Dummy Content");
	_tmp4_ = g_object_ref_sink (_tmp3_);
	_tmp5_ = (GtkLabel*) gtk_label_new ("Tab1");
	_tmp6_ = g_object_ref_sink (_tmp5_);
	_tmp7_ = (GtkLabel*) gtk_label_new ("Tab1MenuItem");
	_tmp8_ = g_object_ref_sink (_tmp7_);
	_tmp9_ = smart_notebook_tab_new_full ((GtkWidget*) _tmp4_, (GtkWidget*) _tmp6_, NULL, TRUE, (GtkWidget*) _tmp8_);
	_g_object_unref0 (tab1);
	tab1 = _tmp9_;
	_g_object_unref0 (_tmp8_);
	_g_object_unref0 (_tmp6_);
	_g_object_unref0 (_tmp4_);
	_tmp10_ = (GtkLabel*) gtk_label_new ("Dummy Content2");
	_tmp11_ = g_object_ref_sink (_tmp10_);
	_tmp12_ = (GtkLabel*) gtk_label_new ("Tab2");
	_tmp13_ = g_object_ref_sink (_tmp12_);
	_tmp14_ = smart_notebook_tab_new ((GtkWidget*) _tmp11_, (GtkWidget*) _tmp13_);
	_g_object_unref0 (tab2);
	tab2 = _tmp14_;
	_g_object_unref0 (_tmp13_);
	_g_object_unref0 (_tmp11_);
	smart_notebook_manager_register_notebook (mgr, nb);
	smart_notebook_manager_store_notebook_tab_positions (mgr, "tabstore.dat");
	smart_notebook_append_tab (nb, tab1);
	smart_notebook_append_tab (nb, tab2);
	smart_notebook_tab_set_reorderable (tab1, TRUE);
	smart_notebook_tab_set_detachable (tab1, TRUE);
	smart_notebook_tab_set_reorderable (tab2, TRUE);
	smart_notebook_tab_set_detachable (tab2, TRUE);
	gtk_container_add ((GtkContainer*) win, (GtkWidget*) nb);
	gtk_window_set_default_size (win, 640, 480);
	gtk_container_set_border_width ((GtkContainer*) win, (guint) 6);
	g_signal_connect ((GtkObject*) win, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) win);
	gtk_main ();
	result = 0;
	_g_object_unref0 (tab2);
	_g_object_unref0 (tab1);
	_g_object_unref0 (nb);
	_g_object_unref0 (mgr);
	_g_object_unref0 (win);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return smart_main (argv, argc);
}



